#!/bin/bash

kidou_dir="$(pwd)"

function kidou()
{
  if [ "$#" -ne 1 ]; then
    echo "usage: kidou <file>"
    return
  fi

  python "$kidou_dir/src/cc/cc.py" $@

  if [ $? -eq 0 ]; then
    "$kidou_dir/bin/vm"
  fi
  
  if [ -f a.out ]; then
    rm a.out
  fi
}
