#!/bin/bash

if [ "$#" -lt 1 ]; then
  echo "usage: $0 <file> [--debug]"
  exit 1
fi

out=$(mktemp)

if [ "$2" = "--debug" ]; then
  kidou-cc "$1" "$out" --dump
  kidou-vm "$out" --debug
  rm "$out"
else
  kidou-cc "$1" "$out"
  kidou-vm "$out"
  rm "$out"
fi
